### ISSUE TITLE
Category Support

### ISSUE THREAD

**Issue by drakej** [klaussilveira/gitlist#380]
It wold be nice to have category support similar to gitweb. On top of that it would be even better if you could expand and collapse a given category (all of them collapsed on page load).

**Comment by v01d** [comment]
I very much also need this feature, due to the large number of repos we have. Categories greatly help browsing the list of repos and gitweb does this nicely. However, gitweb is horrible coded (perl without possibility of templating) and gitlist is the ideal replacement. This and other features (for which I opened issues) are holding me off for switching.
I would try to help but I have no real experience on PHP and it would be mostly a hack.

@drakej, would you consider porting your modification to the latest release maybe? I would be interested in using it.

**Comment by dkozel** [comment]
Categories seem in-line with the viewer mission statement of GitList. I'd benefit in some small ways from being able to organize the list of repositories I have.

**Comment by jissereitsma** [comment]
+1

**Comment by scvandenbraak** [comment]
+1

**Comment by blyk** [comment]
+1 I need this feature badly

**Comment by staffanselander** [comment]
+1

**Comment by JPCodes** [comment]
+1

**Comment by benjaco** [comment]
+1

**Comment by sjoerd-vogel** [comment]
+1

**Comment by Essatt** [comment]
+1

**Comment by AdyKalra** [comment]
+1

**Comment by fubarhouse** [comment]
+1

**Comment by Brian-Webb** [comment]
+1

**Comment by garydamm** [comment]
+1

**Comment by StefanPesic** [comment]
+1

**Comment by sauv0168** [comment]
+1

**Comment by drakej** [comment]
Took a look at this again. My code is off of a stale master checkout and wouldn't work given the changes to add themes as well as it's still a hack which could break and hasn't been well tested. So hopefully the maintainers provide this functionality. I've actually stopped using gitlist because our team is now using Bitbucket instead for private internal repository browsing.

**Comment by sgtpepperpt** [comment]
+1

**Comment by kevin3747118** [comment]
+1

**Comment by wdj-ac** [comment]
+1

**Comment by alireza-hosseini** [comment]
+1

**Comment by blyk** [comment]
Is this ever gonna happen? This thread is 5 year old.

**Comment by alehaa** [comment]
I'm not sure if it makes sense to implement this feature in the current source code of GitList, as we'd like to migrate to Symfony 4 (see #759). However, I plan to integrate this feature in the future.

**Comment by reox** [comment]
Such a feature would also be useful in order to have something like archived repositories.
I have myself a ton of old repositories which I rarely need, and moved them on the git server to /archive/. I do not want to see them directly in gitlist, but sometimes i still want to look something up.
Right now, I hid them all away, also because /archive/ sorts before almost all repos I have, hence I had to scroll through a long list of stale repos.

**Comment by camilstaps** [comment]
@reox you can use #789. I also have an `archived` directory, but with #789 it just shows as a directory instead of listing all repos: https://git.camilstaps.nl/

**Comment by reox** [comment]
@camilstaps looks very promising! Hope I find time to try it out :)

**Comment by larsmagnusny** [comment]
Made a pull request for this issue: [#878](https://github.com/klaussilveira/gitlist/pull/878).

Although the solution @camilstaps suggests might be worth a look, if not add the option to switch between those ways to view the repositories.
