### ISSUE TITLE
Regular expression thinks "readmail" is a README file

### ISSUE THREAD

**Issue by reneemariejones** [klaussilveira/gitlist#482]
In `src/GitList/Util/Repository.php` the following line is trying to detect files that begin "readme":

```php
if (preg_match('/^readme*/i', $file['name'])) {
```

Unfortunately, the \* immediately following the e in readme means it will match anything beginning "readm".  I think you intended:

```php
if (preg_match('/^readme.*/i', $file['name'])) {
```

Better yet, maybe just change it to

```php
if (preg_match('/^readme/i', $file['name'])) {
```

**Comment by lunakid** [comment]
Nice catch & thanks for the details!
I have a closely related one (even though the issue title is too specific to include this, I still add it here instead of opening a new one):

There's README.txt and README-DEV.txt in the repo root.
Unfortunately, the more specific "DEV" one gets picked up,, ignoring the generic README.txt altogether.

That regex should be probably a little more specific (apart from fixing the missing dot, of course).
My current workaround is just: `'/^readme\..*/i'`
