### ISSUE TITLE
Empty RunTime Exception when running getVersion() while viewing a repository.

### ISSUE THREAD

**Issue by uncled1023** [klaussilveira/gitlist#516]
Hello,

I have a couple git repos that it is viewing fine (They show up in the repo list).  I had an older version (0.3.0) and it was able to parse through them correctly.  I upgraded to 0.5.0 from the main page and I am getting the following error when viewing a repo:

```
RuntimeException: 

1. in C:\inetpub\wwwroot\teknik\git\vendor\klaussilveira\gitter\lib\Gitter\Client.php line 86
2.at Client->getVersion() in C:\inetpub\wwwroot\teknik\git\vendor\klaussilveira\gitter\lib\Gitter\Client.php line 65
3.at Client->run(object(Repository), 'branch') in C:\inetpub\wwwroot\teknik\git\vendor\klaussilveira\gitter\lib\Gitter\Repository.php line 164
4.at Repository->getBranches() in C:\inetpub\wwwroot\teknik\git\vendor\klaussilveira\gitter\lib\Gitter\Repository.php line 211
5.at Repository->hasBranch('master') in C:\inetpub\wwwroot\teknik\git\vendor\klaussilveira\gitter\lib\Gitter\Repository.php line 439
6.at Repository->getHead('master') in C:\inetpub\wwwroot\teknik\git\src\GitList\Git\Repository.php line 34
7.at Repository->getHead() in C:\inetpub\wwwroot\teknik\git\src\GitList\Controller\TreeController.php line 19
8.at TreeController->GitList\Controller\{closure}('Tools.git') in C:\inetpub\wwwroot\teknik\git\src\GitList\Controller\TreeController.php line 112
9.at TreeController->GitList\Controller\{closure}('Tools.git')
10.at call_user_func_array(object(Closure), array('Tools.git')) in C:\inetpub\wwwroot\teknik\git\vendor\symfony\http-kernel\Symfony\Component\HttpKernel\HttpKernel.php line 126
11.at HttpKernel->handleRaw(object(Request), '1') in C:\inetpub\wwwroot\teknik\git\vendor\symfony\http-kernel\Symfony\Component\HttpKernel\HttpKernel.php line 66
12.at HttpKernel->handle(object(Request), '1', true) in C:\inetpub\wwwroot\teknik\git\vendor\silex\silex\src\Silex\Application.php line 538
13.at Application->handle(object(Request)) in C:\inetpub\wwwroot\teknik\git\vendor\silex\silex\src\Silex\Application.php line 515
14.at Application->run() in C:\inetpub\wwwroot\teknik\git\index.php line 40
```

Any thoughts?  I ran `git --version` using an elevated command prompt, and it returned `git version 2.1.0`

You can view the old vs new here: https://git.teknik.io/ vs https://gitnew.teknik.io/

Edit: I just tried using the vendors directory from the 0.3 version, and it worked (except when digging deeper and it was missing some of the new functions you are using).  Is there a breaking change in the new vendors?

**Comment by MechaLynx** [comment]
I have the same problem. Here's the [debug output](http://pastebin.com/n7Z77eUM).

Running windows7 x64 sp1, using the standard windows git distribution.

Here's my [config.ini](http://pastebin.com/mcTKUAC5). I have confirmed that the executable is there, works with `--version`, that php has no disabled functions and that it gets the path correctly (I temporarily replaced what the exception returns to the path it gets from `$process`).

I tried the above solution using the development snapshot from the website, since I don't have a built version of 0.3.0. Neither replacing `vendor\symfony\process\Symfony\Component\Process` worked, nor replacing the entire `vendor` directory with the master snapshot one, or just replacing everything with the master snapshot.

**Comment by MechaLynx** [comment]
Confirmed to work with `Symfony\Component\Process` from [this snapshot](https://github.com/symfony/symfony/tree/b89e413a93682a6ce8f6cb3e5d533c7e945172a0) which is the one that would have been bundled with version 0.3.0. Just download the repository and replace that directory in gitlist 0.5.0.

So far no problems.
