### ISSUE TITLE
New contributors

### ISSUE THREAD

**Issue by garygreen** [klaussilveira/gitlist#581]
The project has seen a slowed development for some time. Is it time to possibly look into adding other contributors that would help share the burden of the project, or maintain the issues? 

I would like to volunteer myself, @fauxpark, @NateEag, @sstok

Another idea could be to push for v1.0, define a feature set / move towards a certain goal for the project. @klaussilveira

**Comment by sstok** [comment]
Sorry but I already have a tonnage of other things to do, and I'm not actively using this project anymore (no reason in particular).

**Comment by fauxpark** [comment]
I believe Klaus has some ideas about what's next for Gitlist (and Gitter, I guess), namely a major rewrite in order to make it more modular and easy to customise/theme/etc. But he doesn't appear to have much time on his hands to do it. I think until that work is done, there's not much point making the bigger changes to the current codebase as it's just wasted effort.

But I agree the issue and PR list is getting a bit crowded, and perhaps some of the smaller changes can be merged and more easily translated over to whatever the new structure will be - I recall something said about an adapter-style architecture. I'm happy to help out wherever I can, but I'll probably be a little short on time myself, and my PHP skills are nothing fancy.

**Comment by NateEag** [comment]
I'm no longer an active user and have my plate full with $DAYJOB, family, and side projects.
