### ISSUE TITLE
Online Edit and Commit

### ISSUE THREAD

**Issue by barthoda** [klaussilveira/gitlist#583]
I'm considering using this as a base to add an online edit and commit - like the feature in Github. I was planning on using the ACE editor. Do you have any strong opinions on this?

**Comment by klaussilveira** [comment]
The problem is that GitList is supposed to be a repository viewer. And that's it. Adding write permissions means transforming the project into something it's not, as well adding all the complexity that write operations require: ACL, handling bare repos, redundancy checks, etc.

**Comment by garygreen** [comment]
Agree, I think editing / committing is out of the scope of the project. It might be ok for basic updates, like to readmes etc but you tend to be very limited in what you can do, it's just not worth it. Best to keep it just as a straight & simple viewer.

**Comment by utak3r** [comment]
However editing readmes could be a great addition :)  and it's not violating the "viewer" statement.

**Comment by garygreen** [comment]
@utak3r I think it is violoating the viewer statement. This is best left as a possible addon to gitlist.

**Comment by klaussilveira** [comment]
It is because, technically, in order to implement editing README's, you would have to do everything needed to edit any other kind of file. And it's quite complex, since not everyone is using git in a simple way. There is gitolite and all it's alternatives, there are hook-based ACL, there are remote-handled permissions, etc, etc.
