### ISSUE TITLE
filenames with whitespaces and words starting with b are not correctly recognized

### ISSUE THREAD

**Issue by tribis** [klaussilveira/gitlist#592]
Hi,

In '/src/Gitlist/Git/Repository.php' the regex:
at line 137 readDiffLogs()
```php
$diff = new Diff;
 if (preg_match('/^diff --[\S]+ a\/?(.+) b\/?/', $log, $name)) {
           $diff->setFile($name[1]);
 }
```

fails to match correctly the first file name, when the name has whitespaces and one word starting with b:
For instance wih the filepath:
*copies from other services/new file bname.txt*
the above preg_match will match the diff output as in:
*copies from other services/new file bname.txt b/copies from other services/new file*

which leads to that file getting the wrong name in the filelist.

I've fixed it by me removing the two ? that make the slash after a and b optional. I don't see that it is needed, as I believe that a slash will always be present in the git-diff output.

What is your take on this?

**Comment by JBlond** [comment]
Removing the questionmarks is correct since git diff will provide the a/ ... b/ stuff.

/^diff --[\S]+ a\/?(.+) b\/?/
![orig](https://cloud.githubusercontent.com/assets/2391810/7884107/cec2497c-061b-11e5-92a1-3baff87551f9.png)

vs

/^diff --[\S]+ a\/(.+) b\//
![changed](https://cloud.githubusercontent.com/assets/2391810/7884111/d87e82be-061b-11e5-9512-90f937f7fa7c.png)

**Comment by tribis** [comment]
Nice visualisation. Than kyou
