### ISSUE TITLE
Github says it's not a repository when trying to checkout

### ISSUE THREAD

**Issue by jkleve** [klaussilveira/gitlist#598]
I'm trying to checkout an older version of the ArduPilot library by running the command "git clone 03373d35c29d299356a3d80f262f335e8f100814" but get the error 
"fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)."

Anyone know why this would be?

**Comment by brunogaspar** [comment]
The title is most likely incorrect, it's not GitHub that's giving the error but rather Git.

Regarding your problem, i'm not quite sure what you're trying to achieve here, you say you want to checkout but you're using the `git clone` command, confusing.

But anyway, for cloning you'll need to clone by a URL not by a commit SHA, like `git clone git@github.com:klaussilveira/gitlist`.

For doing a checkout, it's recommended to checkout by a branch name, and not by a commit SHA otherwise you'll be on a "detached head" state, but you can try either with `git checkout branch-name-here` or with `git checkout SHA-HERE`.

**Comment by jkleve** [comment]
Ah ok sorry about all the mistakes. Yes I'm talking about Git and I'm not using clone. So to re-specify the command I'm trying is "git checkout 03373d35c29d299356a3d80f262f335e8f100814" That gives me there error you see about. I got that SHA from this site https://github.com/diydrones/ardupilot/tree/ArduCopter-3.2.1

**Comment by brunogaspar** [comment]
Works fine here.

```
➜  ~  git clone git@github.com:diydrones/ardupilot
Cloning into 'ardupilot'...
remote: Counting objects: 119960, done.
remote: Total 119960 (delta 0), reused 0 (delta 0), pack-reused 119960
Receiving objects: 100% (119960/119960), 65.14 MiB | 4.34 MiB/s, done.
Resolving deltas: 100% (84716/84716), done.
Checking connectivity... done.
➜  ~  cd ardupilot
➜  ardupilot git:(master) git checkout 03373d35c29d299356a3d80f262f335e8f100814
Note: checking out '03373d35c29d299356a3d80f262f335e8f100814'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 03373d3... AutoTest: Add ability to run AC3.2.1 in screen
➜  ardupilot git:(03373d3)
```

Try to checkout by the branch name or checkout to the master branch then checkout for the specific commit.

**Comment by garygreen** [comment]
Closing as not issue with gitlist.
