### ISSUE TITLE
GitList Development

### ISSUE THREAD

**Issue by tuxy** [klaussilveira/gitlist#607]
Is this project still get updates or you abandoned it ? Because this is the best GitHub clone I've seen besides GitLab which is over-bloated and very heavy for small projects. GitList seems like a perfect clone in php, but it needs more features like private repos, issue tracker and better admin/user/guest.

**Comment by dkozel** [comment]
I can't comment on the development status, things have seemed quiet for over 6 months now. @garygreen was interested in bringing more of the community in to move development along in https://github.com/klaussilveira/gitlist/issues/581.

However the main developer has stated that he is not interested in having an issue tracker, editor, or other interactive elements as part of GitList. GitList is *only* a display interface for repositories. However private repositories, and thus some sort of authentication interface, is probably within scope for the project so if development resumes then code contributions implementing those would probably be welcomed.

**Comment by garygreen** [comment]
I would welcome an issue tracker, but as for editing repositories I think it has very limited usages so would always be low priority as Gitlist is primarily a viewer/reader. It would be more suited to some kind of addon to gitlist.

I'd love to see more involvement in the project, there's definitely interest from the community but as you say, the main developer has been inactive for a while (there are talks about another gitlist being rewritten from scratch, but not sure how far things got with that).

The main issue is little to no communication with the direction of the project. The PRs are being left (despite fixing a number of major issues), and no issues being responded to.

I would happily volunteer to help boost the project and bring it along, but without any thoughts from @klaussilveira it looks unlikely to happen.

**Comment by DannyvdSluijs** [comment]
I'm more than happy to help as well. Would it be an idea to talk together about such undertaking and start with some basic requirements gathering. And other basics such as are we planning to fork from Gitlist or start from scratch.

And see how many people are committed to participate and to what extend. 

I'm still very pleased with what Gitlist offers but I believe there is a large community driven demand to have items such as issue tracker, authentication & authorization. Personally I would also opt for a commit review / feedback possibility.

**Comment by klaussilveira** [comment]
As of now, the project needs some major refactoring. Specially since the maintainability of the project is so complex right now, it's difficult to add the highly required caching layer. I'm trying to find some time to dedicate to the project, but it's difficult. Everytime i start working on it, i end up rewriting major parts of the codebase and one thing leads to another. The project is not dead, it's just dormant. 

But you can rest assured that, in the next version, we'll allow some sort of plugin system, allowing everyone to make their own extensions to GitList and add features that are not within the scope of the project (write operations on top of repositories, login/ACL, etc). I don't want to add unnecessary complexity to the codebase, but people really want those kinds of features.

**Comment by garygreen** [comment]
@klaussilveira Is there anything the community can do to help with the development? There is a number of PRs here that have been awaiting review for some time. If it's a case of all development on this project will be inactive until the complete rewrite, can you at least confirm that is the case / your intention?

I think it's just a frustration of not being able to contribute because of this rewrite which may or may not even come to fruition (due to time constraints etc).

I'm more than happy to go through (at least) the issues and help out but there's only so much you can do when PRs aren't being looked at / responded to etc. Really appreciate all your hard work on this project, just wish there was more we could do to help lighten the burden. :smile:

**Comment by dkozel** [comment]
@klaussilveira Thanks for giving us an update.

Would you consider creating a new minor version release incorporating a few of the pull requests which are quite small but address high impact problems such as repositories with '-' in their name? Here are two examples of such. https://github.com/klaussilveira/gitlist/pull/589 https://github.com/klaussilveira/gitlist/pull/554

**Comment by klaussilveira** [comment]
The real problem is that all those solutions seem like... duck tape. The regexes are unnecessarily complex and will come after us in the future. Same for the escaping/filtering strategies. A major refactoring in both areas is necessary to keep things going forward in a sane way.

However, i am thinking about splitting 0.X from 1.x. Since GitList never had a major release, this could be easy. What are your considerations for this? Would you prefer a repository split, or just keep `master` with 1.x and a new `legacy` branch with the current codebase?

**Comment by tuxy** [comment]
@klaussilveira Yes please split this into two repositories, legacy (old) and master (new).
Also can you change your license to MIT ? Thank you.

**Comment by garygreen** [comment]
I really dislike repository splitting, confuses a lot of people. I'd opt for new branch for v1.

**Comment by garygreen** [comment]
As for the duct tape comment, I'd sooner have a duct tape fix for a major issue until we can work out a more efficient solution. To me delaying big issues until v1 is not a good idea. At least go through the PRS if people have put time into fixing them.

**Comment by erez-o** [comment]
if a serious amount of code would be different, and the api will change as well, I think a split of repositories is better.

@klaussilveira , I think that if you split the project into separate modules, different contributors can work on each module separately contributing to the logetivity of the project. 

Another way is to for you to design the project around gitweb, which is promised to be well maintained.

I've seen too many great projects die because they became too big and too dependent on their main author, and I will be sudden if this becomes one of them.

**Comment by klaussilveira** [comment]
The project is open, though. It's just that the guys that used to contributed, like Wim and Dave are also busy with other projects and so on. If anyone is willing to help review pull requests, clean some parts of the code, etc, just tell me and i'll add you to the repository contributors list. If you're not secure about coding, you can also contribute by organizing/cleaning issues and so on. 

Regarding to split or not to split, this demands a separate thread: https://github.com/klaussilveira/gitlist/issues/608

**Comment by garygreen** [comment]
@klaussilveira thanks. Would you mind adding me as a contributor so I can review the PRs?
