### ISSUE TITLE
Files containing cp949 characters are not shown.

### ISSUE THREAD

**Issue by KuddLim** [klaussilveira/gitlist#632]
I just installed gitlist 0.5.0 on my server and this is really cool. 
But it cannot display some files those have non utf-8 characters.

This is MFC-generated file which contains some comments in korean (cp949)
![gitlab1](https://cloud.githubusercontent.com/assets/9252346/10776659/b4793ba4-7d56-11e5-80f6-1f08d5ae568c.png)

When I convert that file to utf-8, gitlist shows it well.

I'm not saying gitlist should convert non-utf8 files to utf8.

Should I see these files in raw format??

**Comment by KuddLim** [comment]
I'm annoyed. 
When I change cp949 characters to utf-8, I can see  changeset with cp949 characters.

![gitlist2](https://cloud.githubusercontent.com/assets/9252346/10777394/69c6176e-7d5e-11e5-8134-239c401a119e.png)

**Comment by jahir** [comment]
I have the same problem with latin1 encoded files. Given that this issue is almost 3 years old, I guess there's little hope that it will be solved.
The reason is probably that gitlist (or the functions it uses) use UTF-8 by default and one of them bails because most latin1 specific characters are invalid UTF-8. There is probably some way to tell them the correct encoding (or convert it to utf8 before), but I could not find the right place... some hint would be highly appreciated.

**Comment by jahir** [comment]
turns out there is a way to tell git which encoding a file uses: set `working-tree-encoding` in _.gitattributes_. git will then convert the file content into UTF-8 before storing it and convert it back to the specified encoding when checking it out. This works with gitlist, because gitlist seems to retrieve the stored content without conversion, so the default encoding given by gitlist (utf8) is fortunately correct.
Only problem is that all the files are already stored as non-utf8 in the repo. Luckily, there is [a way to fix that](https://stackoverflow.com/questions/11052199/convert-git-repository-file-encoding)
