### ISSUE TITLE
why is this hosting on github?

### ISSUE THREAD

**Issue by Goddard** [klaussilveira/gitlist#639]
Just curious why you don't eat your own dog food?

**Comment by klaussilveira** [comment]
Because GitList is not a replacement or an alternative to GitHub. GitList is like gitk, but for the web. No issues, no wiki, no ACL, no pull requests, no editing. 

If you are looking for something like GitHub, i suggest you take a look at GitLab, Phabricator or Gitonomy. They're great projects and even present new feature sets.

**Comment by SkeletonEye** [comment]
In my opinion, one could close this issue since the question has been answered.
