### ISSUE TITLE
Listing repository fails if its directory name contains a dot character

### ISSUE THREAD

**Issue by lvic** [klaussilveira/gitlist#708]
Exception in index.twig at line 16 while rendering template: "param repo must match 'abc\\.git' ('abc.git' given)":
![gitlibbug](https://cloud.githubusercontent.com/assets/9221213/21199831/691b1ea4-c245-11e6-856a-bbe8280d6c3f.PNG)

my workaround: removed the dot (and the git ;) in the name of the repository folder:
![image](https://cloud.githubusercontent.com/assets/9221213/21200179/b4af984e-c246-11e6-9a93-3039b305d248.png)

possible solution to this issue: escaping/encoding the name of the directory while passing it as a parameter?
best regards

**Comment by jk3us** [comment]
This seems to happen if there is a hyphen in the name.  I cloned lucene-solr, and got a similar error.  I renamed the dir to lucene_solr and it worked fine. (I'm currently using the 0.5.0 tag)

**Comment by dartero** [comment]
Related to this, as it's a parsing filenames issue, when a repository has a name consisting only in numbers (...repositories\111\.git) returns an error:

**Notice:** Undefined offset: 111 in **...\src\Git\Client.php** on line **24**

Taking a look at that file and the one at gitter include, seems like is caused by a type mismatch, as it tries to get "filename" assuming a string, but when only numbers are present "automatically" gets converted to an integer, so it performs a lookup of the 111th item in vector.

I'm using Gitlist on XAMPP (PHP 7.2.8) on Windows
