### ISSUE TITLE
not able to overwrite built-in binary filetype

### ISSUE THREAD

**Issue by elisiano** [klaussilveira/gitlist#743]
I am using gitlist as a frontend to rancid, which saves the file with the same hostnames found in its configuration.
The filename is like `hostname.domain.com`.
This is what I tried (unsuccessfully)

```
[...]
[filetypes]
com = cfg

[binary_filetypes]
com = false
[...]
```
I also tried some variants of the above but everytime I click on the file it gets downloaded instead of shown as text.

How can I achieve that?

I'm using GitList 0.6.0

**Comment by alehaa** [comment]
Possibly related to #736?

**Comment by elisiano** [comment]
@alehaa apologies for my ignorance but can you explain how they relate?

**Comment by DannyvdSluijs** [comment]
This is due to the order in the Util class. (See https://github.com/klaussilveira/gitlist/blob/cc1dc5af14e83dc7ca602694a1d2bfb7878d3aa8/src/Util/Repository.php)
Defaults are checked first in no result addditions are checked. Currently you can't overload that the extension `.com` is seen as a binary type, hence the forced download.

This seems to be an improvement possible here where the config filetypes and binary_filetypes should be checked before the application defaults. This would allow overloading. I'll check the #736 if this is the same issue.

**Comment by alehaa** [comment]
@elisiano The issues seem to be related, as both of you can't overwrite filetypes.

**Comment by DannyvdSluijs** [comment]
In #736 it is confirmed that adding extra filetypes works. As the html contains `<pre id="sourcecode" language="twig"> ... </pre>`. The code mirror lib we are using is rather old and doesn't support Twig yet.
