### ISSUE TITLE
gitlist.org doesn't ship latest version

### ISSUE THREAD

**Issue by ArthurBorsboom** [klaussilveira/gitlist#755]
I have downloaded gitlist from [http://gitlist.org/](http://gitlist.org/)

![2017-10-31-222021_280x172_scrot](https://user-images.githubusercontent.com/6639859/32249578-d929e8ce-be89-11e7-8b7e-df5935ecca80.png)

It states v0.5.0 on the website and the filename in my browser is the same.

![2017-10-31-222003_217x35_scrot](https://user-images.githubusercontent.com/6639859/32249624-f5cc625e-be89-11e7-9e77-d95f385bbfa6.png)

However, after installing and configuring the version on the bottom of my live webpage shows a different version number.

![2017-10-31-221944_181x61_scrot](https://user-images.githubusercontent.com/6639859/32249687-230804bc-be8a-11e7-9508-7841e19ce367.png)

Which one is the correct one? :)
How can I verify which version I am really using?

**Comment by alehaa** [comment]
Seems like the website is outdated. You can find `v0.6.0` in the releases tab of this repository. The `0.4.0` label comes from an older bug (see #654).

**Comment by lunakid** [comment]
Hello, why is this closed? 
This is still a problem, and a very confusing one.

The README definitely *shouldn't* misleadingly say: **"Download GitList from gitlist.org..."**
I obeyed, overriding my personal preference of grabbing it right from the GitHGub, and (even though I did learn about that forgotten 4.0 version label earlier), I just realized, after "upgrading" the documented way again, that I've been avtually using the same, unchanged "canonical" dev version for over year...

**Comment by lunakid** [comment]
Ah, damn, true, sorry! :)) (In fact, I though about that, but couldn't quite decide, because I did also see that red "Closed" button at the bottom, which was kind of the last "action-like" thing displayed for the page, and even though I considered that it may have belonged to that #364 on the same line, my tired brain rejected that idea, and accepted an even more unlikely one, that the big green button at the top is somehow just an artifact of GitHub... :) )

**Comment by agilare** [comment]
The last version is 0.7 but gitlist.org download button shows : 

> Latest stable (0.5.0)
