### ISSUE TITLE
Markdown _text_ is not rendered as italic

### ISSUE THREAD

**Issue by quixotique** [klaussilveira/gitlist#763]
But it _works in GitHub_.

**Comment by alehaa** [comment]
I'm not sure, but isn't italics with underscores GitHub flavored markdown instead of regular markdown?

Showdown.js is configured to parse regular markdown. However, you can simply change it to render GitHub flavored markdown instead by adding 
```JavaScript
converter.setFlavor('github');
```
in [main.js after line 24](https://github.com/klaussilveira/gitlist/blob/master/themes/bootstrap3/js/main.js#L24).

**Comment by quixotique** [comment]
Single underscores should produce the `<em> ... </em>` span element in standard Markdown, which is usually rendered as italic.

**Comment by siburny** [comment]
Showdown is already setup for single underscores or single asterisks to produce <em> tag.
