### ISSUE TITLE
PHP Fatal error:  Cannot use 'Object' as class name

### ISSUE THREAD

**Issue by jundi** [klaussilveira/gitlist#765]
Gitlist home page works normally (I can see the list of repositories) but when I open any of the repositories I get just a blank page. In PHP logs I have an error message:
` PHP Fatal error:  Cannot use 'Object' as class name as it is reserved in /usr/local/share/gitlist/vendor/klaussilveira/gitter/lib/Gitter/Model/Object.php on line 14`

This happens on Arch linux with PHP 7.2.1.

**Comment by alehaa** [comment]
@jundi this is an issue of Gitter. Please file an issue [here](https://github.com/klaussilveira/gitter/issues).

**Comment by justinhartman** [comment]
> @jundi this is an issue of Gitter. Please file an issue [here](https://github.com/klaussilveira/gitter/issues).

What do you mean this is an issue of gitter? This is clearly an issue of gitlist as it depends on gitter and this has been resolved in that package. You need to update gitter in order to run gitlist on PHP 7.2. I know you maintain both packages but surely gitlist needs to be updated to use the latest code from gitter?

A default install on PHP 7.2 from gitlist 1.0.1 stable returns the `Fatal error: Cannot use 'Object' as class name as it is reserved in /vendor/klaussilveira/gitter/lib/Gitter/Model/Object.php on line 14`. However, updating the vendor folder has a different result.

For example:

```console
$ git clone https://github.com/klaussilveira/gitlist.git
$ cd gitlist
$ composer install
$ mv vendor /path/to/gitlist/stable/1.0.1/
```
When you have moved the vendor folder to gitlist stable then the error disappears and you can actually browse the repositories. There is a new warning, however, that says `Warning: Declaration of GitList\Git\Repository::getStatistics($branch) should be compatible with Gitter\Repository::getStatistics() in /src/Git/Repository.php on line 11` but despite the warning, the software at least works on PHP 7.2.

As you know, the `Object.php` file in gitter has been replaced with `GitObject.php` which is a fix for PHP 7.2 so I don't understand why you don't integrate these changes into gitlist so that people running 7.2 can use your software?

Anyway, just my thoughts on the matter, use it or not but it would make sense to integrate the vendor changes so this works on 7.2.

**Comment by lunakid** [comment]
Yes, please release a 7.2 compatible version with the updated `gitter`.

@justinhartman: to fix the "Warning" you mentioned, I just copied the entire `src` dir from the current `master` over the last (1.0.1) release (after doing the same for `vendor/.../gitter`, too, of course).

So, by a quick look (and some smoke test), the current state of the repo may actually be 7.2 compatible as-is, so, if yes, hopefully a new release will soon be created to make it official.

**Comment by ahorseman** [comment]
Any news on this? Facing same issue on 7.2...

**Comment by justinhartman** [comment]
@ahorseman you could follow [my hack in this comment] (https://github.com/klaussilveira/gitlist/issues/765#issuecomment-427969507) if you need an urgent workaround to get the software working.

**Comment by fdp2** [comment]
@justinhartman thanks for your input here.
It's pitty that the package is not updated. This lead to people thinking that the tool is no more maintained even if Most of the job is already done, it's just a matter of packaging.

**Comment by alehaa** [comment]
You can download a new version from the releases page - or just run composer yourself.
