### ISSUE TITLE
Future of GitList

### ISSUE THREAD

**Issue by alehaa** [klaussilveira/gitlist#879]
I'm pretty unsure on the status of this repository. As Silex is End-Of-Life, we can't provide any new releases without porting to Symfony. So what's the deal? Is this repository archived?

As you originated the project, I'd like to pass the question to you @klaussilveira.

**Comment by klaussilveira** [comment]
I'm going to push a beta Symfony 5 version of GitList soon. It has been hard to find enough time to test many repositories, as well as different paths and tree structures. The most buggy feature is proper routing. That version should allow people that are interested in the project to contribute using modern PHP concepts. 

As for `1.x`, I intend to maintain this for as long as possible. Hopefully with a beta `2.x`, stability-focused PRs will be more common for `1.x`. As for the bug tracker, is a tag/milestone enough to separate issues? What do you guys think?

**Comment by walter-exit** [comment]
@klaussilveira I'm looking forward to a new release. We had to upgrade to PHP 8 internally, and since then GitList has unfortunately down on our intranet. We would love to get it working again.

**Comment by klaussilveira** [comment]
The goal of 1.x is, definitely, compatibility and stability. Currently working on a new release that would satisfy as many people as possible.

**Comment by Fred-Zweig** [comment]
Hello! Thank you for developing GitList. And thank you for choosing PHP to develop it.

I consider GitList to be the best self-hosted alternative to GitHub, on the whole Internet. This is because all the other projects (GitLab, Gitea, Gogs, Fossil, GitPrep, Gitblit, Allura, Kallithea, GitBucket, etc.) either use suboptimal programming languages like Ruby or Java, either use a language created by Google and controlled by Google called Go, either use Perl and are full of bugs, either mix their code with the terrible mistake in server-side web programming called node.js, either have a very ugly interface. I haven't tried them all, but for me it's enough to know that the developer(s) chose the wrong programming language for the job, to realize that the project can't be trusted. The only viable PHP based alternatives seemed to be Tuleap and Phabricator. Unfortunately Tuleap cannot be installed on other OSs than CentOS and it needs an entire server. Also, we learn from Wikipedia that Phabricator was developed by a former Facebook employee (which is enough to loose trust in the application), and that in May 2021, the company that maintained it ceased operations, So, the only self-hosted viable alternative to GitHub, written in the best language for web programming, is GitList.

Please, don't abandon GitList! It is highly needed. It looks quite good as it is. **Also, please make it compatible with PHP 8**, because it would be a pity to have to abandon GitList after I spent so much time to find it, install it and configure it, just because I upgrade PHP from 7 to 8 (probably in a few months).

If you maintain GitList further and make it compatible with PHP 8 I'm going to advertise it on my website and bring new users to GitList. I've already drafted an installation guide. I'll probably urge new users to donate to your project, if you have a donation page.

As about the bug tracker, I plan to install [Mantis Bug Tracker](https://www.mantisbt.org/) and connect it with GitList. Mantis is also written in PHP and it seems to have a good reputation. Maybe, instead of developing your own bug tracker you can just integrate Mantis into GitList.

**Comment by MacHoel** [comment]
> @klaussilveira I'm looking forward to a new release. We had to upgrade to PHP 8 internally, and since then GitList has unfortunately down on our intranet. We would love to get it working again.

Hi, check #880 for PHP8 compatibility, might solve your issue with the current gitlist.

**Comment by klaussilveira** [comment]
It should now: https://github.com/klaussilveira/gitlist/releases/tag/1.1.0

**Comment by Fred-Zweig** [comment]
Thank you very much for this new GitList realease compatible with PHP 8. I maintain my opinion that GitList is the best self-hosted alternative to GitHub. Therefore, it's needed by all who want an efficient and good-looking git viewer on a LEMP stack. Please, whatever you do with GitList in the future, don't mix it with node.js.

**Comment by klaussilveira** [comment]
I just shipped a draft of what 2.0 should look like. There are many features missing and work needs to be done, but most of the architecture is laid out and provides a base for the project to continue to exist. It simply wasn't feasible to continue supporting the legacy version with so many changes in the ecosystem. 

https://github.com/klaussilveira/gitlist#legacy

Hopefully, this answers some of the questions about what the future of GitList should look like and how it can continue to exist.

**Comment by Fred-Zweig** [comment]
@klaussilveira  Can I install and use GitList 2.0 without installing Node.js ?

**Comment by klaussilveira** [comment]
Use the release build, not the source: https://github.com/klaussilveira/gitlist/releases

**Comment by Fred-Zweig** [comment]
Ok, but in the future, for GitList 3.0, 4.0 etc., will I be able to use GitList without installing Node.js ?

**Comment by klaussilveira** [comment]
Node.js is used for development purposes, same as Composer. It won't be required for the application to run.

**Comment by Fred-Zweig** [comment]
Ok, thank you for your reply. I understand that GitList 2.0 and future versions will be able to integrate with Node.js if a developer will want to add some frontend features that require Node.js on the backend, but Node.js won't be required for the functioning of unmodified GitList. Is this correct ?

**Comment by klaussilveira** [comment]
Correct.
